apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbooster-browser-use
  annotations:
    iam.gke.io/gcp-service-account: testbooster-ai@testbooster.iam.gserviceaccount.com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbooster-browser-use
  template:
    metadata:
      labels:
        app: testbooster-browser-use
    spec:
      serviceAccountName: web-ui-ksa
      containers:
        - name: web-ui
          image: us-east1-docker.pkg.dev/testbooster/testbooster-browser-use/testbooster-browser-use:0.0.10
          ports:
            - containerPort: 9090
          envFrom:
            - secretRef: { name: testbooster-browser-use-env }
          resources:
            requests:
              cpu: "250m"     # garante agendamento
              memory: "512Mi"
            limits:
              cpu: "1000m"    # até 1 vCPU
              memory: "1536Mi"   # até 1.5 GB
          readinessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 15