apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbooster-browser-use
  annotations:
    iam.gke.io/gcp-service-account: testbooster-ai@testbooster.iam.gserviceaccount.com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbooster-browser-use
  template:
    metadata:
      labels:
        app: testbooster-browser-use
    spec:
      serviceAccountName: web-ui-ksa
      containers:
        - name: web-ui
          image: us-east1-docker.pkg.dev/testbooster/testbooster-browser-use/testbooster-browser-use:0.0.11
          ports:
            - containerPort: 9090
          envFrom:
            - secretRef: { name: testbooster-browser-use-env }
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              cpu: "500m"   # 0.5 vCPU garantida
              memory: "1Gi"   # 1 GiB garantido para agendamento
            limits:
              cpu: "2000m"  # até 2 vCPUs
              memory: "4Gi"    # até 4 GiB de RAM
          readinessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 15
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
